spring:
  redis:
    host: 39.105.37.47
    port: 6378
    database: 0
    password: redis@zhangbin
  data:
    mongodb:
      # 格式mongodb://用户名:密码@39.105.37.47:27016/数据库
      uri: mongodb://zhangbin:123456@39.105.37.47:27016/mydb
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456


  rabbitmq:
    host: 39.105.37.47
    port: 5672
    username: mymq
    password: 123456

#  kafka:
#    bootstrap-servers: 39.105.37.47:9092
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: my_test
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  enable: false
  whitelists:
    - /user/msg
    - /user
    - /direct/amsg/**
